version: "3.9"

services:
  db:
    image: yzh44yzh/wg_forge_backend_env:1.1
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - WAIT_HOSTS=db:5432
