# Generated by Django 4.0.5 on 2022-07-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatColorsInfo',
            fields=[
                ('color', models.TextField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'cat_colors_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('color', models.TextField(blank=True, null=True)),
                ('tail_length', models.IntegerField(blank=True, null=True)),
                ('whiskers_length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatsStat',
            fields=[
                ('tail_length_mean', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('tail_length_median', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tail_length_mode', models.TextField(blank=True, null=True)),
                ('whiskers_length_mean', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('whiskers_length_median', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('whiskers_length_mode', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cats_stat',
                'managed': False,
            },
        ),
    ]
